# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _scss
  style:            :compressed
collections:
  videos:
    output: true
defaults:
  -
    scope:
      path: ""
      type: "videos"
    values:
      layout: "video"
